config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:update, :edit, :destroy, :show]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    #list = List.new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    # @list = List.new(list_params)
    @list = current_user.lists.build(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to list_url(@list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def correct_user
    @list = current_user.lists.find_by(id: params[:id])
    redirect_to lists_path, notice: "Not Authorized" if @list.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
  <%= link_to 'friend app' , root_path , class:"navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
        <%= link_to 'About Us' , home_about_path , class:"nav-link"  %>
        </li>
        <% if user_signed_in? %>
           <li class="nav-item">
           <%= link_to 'List of friends' , lists_path , class:"nav-link"  %>
           </li>
           <li class="nav-item">
           <%= link_to 'Sign out', destroy_user_session_path , :method => 'delete', class:"nav-link" %>
           </li>
           <li class="nav-item">
           <%= link_to 'Edit profile' , edit_user_registration_path , class:"nav-link"  %>
           </li>
        <% else %>
          <li class="nav-item">
          <%= link_to 'Sign Up' , new_user_registration_path , class:"nav-link"  %>
          <li class="nav-item">
          <%= link_to 'Sign In' , new_user_session_path , class:"nav-link"  %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Page</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<p>This is my first rail projects</p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
        <div style="height: 3.5rem; margin-block: .5rem; position: relative;">
      <% if notice %>
        <div style="position: absolute; width: 100%;" id="notice">
          <%= render 'layouts/alert' %>
        </div>
      <% end %>
        </div>
     <%= yield %>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script>        
        const notice = document.getElementById("notice")
        if (notice) {
          setTimeout(() => {
            notice.style.display = "none"
          }, 2500);
        } 
    </script>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, class:"form-label" %>
    <%= form.text_field :first_name , class:"form-control" %>
  </div>
  <%# <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Email address</label>
  <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div> %>
  <div class="mb-3">
    <%= form.label :last_name , class:"form-label" %>
    <%= form.text_field :last_name, class:"form-control"  %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class:"form-label" %>
    <%= form.text_field :email , class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, class:"form-label" %>
    <%= form.text_field :phone , class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :twitter, class:"form-label" %>
    <%= form.text_field :twitter , class:"form-control" %>
  </div>
  <div class="mb-3">
    <%= form.number_field :user_id ,id: :list_user_id , value:current_user.id, type: :hidden %>
  </div>
  <div class="mb-3">
    <%= form.submit class:"btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
  <th>
    <a href="/lists">
      <%= link_to list.first_name + " " + list.last_name , list , class:"friend-name" %>
    </a>
  </th>
  <td>
    <%= list.email %>
  </td>

  <td>
    <%= list.phone %>
  </td>

  <td>
    <%= list.twitter %>
  </td>
  <td>
    <%= list.user_id %>
  </td>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<h1>Lists</h1>
<div id="lists">
<table class="table table-striped table-bordered table-hover">
<thead class="table-dark">
<tr>
<th scope="col">Name</th>
<th scope="col">Email</th>
<th scope="col">Phone</th>
    <th scope="col">Twitter</th>
    <th scope="col">Created by</th>
</tr>
</thead>
    <tbody class="table-group-divider">
  <% @lists.each do |list| %>
      <% if list.user == current_user %>
          <tr id="<%= dom_id list %>">
            <%= render list %>
          </tr>
      <% end %>
  <% end %>
    </tbody>
</table>
</div>

<%= link_to "New list", new_list_path , class:"btn btn-secondary" %>

app/views/lists/new.html.erb
<h1>Add new friend</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="card w-75">
  <div class="card-body">
    <h5 class="card-title"><%= @list.first_name %> <%= @list.last_name %></h5>
    <p class="card-text">
    <strong>Email address :</strong> <%= @list.email %>
    </p>
    <p class="card-text">
    <strong>Phone Number :</strong> <%= @list.phone %> 
    </p>
    <p class="card-text">
    <strong>Twitter Account :</strong> <%= @list.twitter %> 
    </p>
    <div>
       <%= link_to "Edit this list", edit_list_path(@list) , class:"btn btn-secondary" %> 
       <%= link_to "Back to lists", lists_path , class:"btn btn-secondary" %>
       <%= button_to "Destroy this list" , @list, method: :delete , class:"btn btn-warning my-1" %>     
    </div>
  </div>
</div>